**Write a Python program which accepts a list named : randomList = ['a', 0, 2]. Use exception handling using try-catch which gives the output as:**

Output:

1) If the List element is a alphabet or string, the output will be
The entry is a
Oops! <class 'ValueError'> occured.
Next entry.

2) If the List element is “0”,the output will be
The entry is 0
Oops! <class '  '> occured.
Next entry.

3) If the List element is and integer except 0,then output will be:
The entry is 2
The reciprocal of 2 is 0.5 // reciprocal of an integer

In [2]:
import sys

randomList = ["a", 0, 2]

for i in randomList:
    try:
        print("The entry is", i)
        r = 1/int(i)
        break
    except:
        print("Oops!", sys.exc_info()[0], "occured.")
        print("Next entry.")
        print()

print("The reciprocal of", i, "is", r)

The entry is a
Oops! <class 'ValueError'> occured.
Next entry.

The entry is 0
Oops! <class 'ZeroDivisionError'> occured.
Next entry.

The entry is 2
The reciprocal of 2 is 0.5

**Array out of Bound Exception**

Write a Python program to give exception “Array Out of Bound” if the user wants to access the elements beyond the list size (use try and except)

In [3]:
list_random_numbers = [1, 2, 3, 4, 5]

try:
    print(list_random_numbers[0])
    print(list_random_numbers[10])
except IndexError as error:
    print("Exception: Array Out of Bound")

1
Exception: Array Out of Bound

**Write a python module script that contains fib2() method to calculate the Fibonacci series till 1000 and save it as fibo.py.**

Note : The module created as fibo.py has to be placed in lib folder

For linux/ubuntu path = /home/anaconda/lib/python3
For Windows path = C:/Users/Ajit/Anaconda3/Lib

In [4]:
def fib2(n):
    sequence = []
    a, b = 0, 1
    while b < n:
        sequence.append(b)
        a, b = b, a + b

    return sequence

# This file can be saved as fibo.py, Function fib2() can be used generate Fibonacci series after importing file.

**Write a python module script that contains ispalindrome() method to calculate the input string as palindrome string or not and save it as palindrome.py.**

In [5]:
def ispalindrome(s):
    if s[::-1] == s:
        return True
    else:
        return False

# This file can be saved as palindrome.py, Function ispalindrome() can be used to check palindrome string after importing file.

**Write a program in Python with one class called Cipher. Within the constructor of this class, ask user for a string and store it.**

Use a static variable, key to store a randomly generated integer between 1 and 50 inclusive. 
Implement two methods, encrypt and decrypt within this class. 
Encrypt generates and prints a cipher text using the user-entered string and the key and ecrypt generates decrypted string from ciphertext. 

The cipher only encrypts alpha and numeric (A-Z, a-z, 0-9). All Symbols, such as - , ; %, remain unencrypted.
The cipher text can have special characters. Use generator expression to filter out alpha and numeric characters of the input string and to generate cipher text. 

Create an instance of this class, encrypt and decrypt back the user entered string.

In [6]:
import random

class Cipher():
    key = random.randint(1,51)

    def __init__(self, text):
        self.text = text
        self.encrypted_text = ""

    def encrypt(self):
        result = ""
        for i in range(len(self.text)):
            char = self.text[i]
            if (char.isupper()):
                result += chr((ord(char) + Cipher.key - 65) % 26 + 65)
            else:
                result += chr((ord(char) + Cipher.key - 97) % 26 + 97)

        self.encrypted_text = result
        return self.encrypted_text

    def decrypt(self):
        result = ""
        for i in range(len(self.encrypted_text)):
            char = self.encrypted_text[i]
            if (char.isupper()):
                result += chr((ord(char) - Cipher.key - 65) % 26 + 65)
            else:
                result += chr((ord(char) - Cipher.key - 97) % 26 + 97)

        return result

text = input("Input any string: ")
print("\nText = ", text)

c = Cipher(text)
print("Encrypted = ", c.encrypt())
print("Decrypted = ", c.decrypt())

Input any string: KAmlesh

Text =  KAmlesh
Encrypted =  GWihaod
Decrypted =  KAmlesh

**Get Data from the following link:**
http://files.grouplens.org/datasets/movielens/ml-20m.zip

We will be using the following files for this exercise:

ratings.csv : userId,movieId,rating, timestamp<br />
tags.csv : userId,movieId, tag, timestamp<br />
movies.csv : movieId, title, genres<br />

I. Read the dataset using pandas.<br />
II. Extract the first row from tags and print its type.<br />
III. Extract row 0, 11, 2000 from tags DataFrame.<br />
IV. Print index, columns of the DataFrame.<br />
V. Calculate descriptive statistics for the 'ratings' column of the ratings DataFrame. Verify using describe().<br />
VI. Filter out ratings with rating > 5<br />
VII. Find how many null values, missing values are present. Deal with them. Print out how many rows have been modified.<br />
VIII. Filter out movies from the movies DataFrame that are of type 'Animation'.<br />
IX. Find the average rating of movies.<br />
X. Perform an inner join of movies and tags based on movieId.<br />
XI. Print out the 5 movies that belong to the Comedy genre and have rating greater than 4.<br />
XII. Split 'genres' into multiple columns.<br />
XIII. Extract year from title e.g. (1995).<br />
XIV. Select rows based on timestamps later than 2015-02-01.<br />
XV. Sort the tags DataFrame based on timestamp.<br />

I. Read the dataset using pandas.

In [7]:
import pandas as pd

df_ratings = pd.read_csv("./ml-20m/ratings.csv")
df_tags = pd.read_csv("./ml-20m/tags.csv")
df_movies = pd.read_csv("./ml-20m/movies.csv")

II. Extract the first row from tags and print its type.

In [8]:
type(df_tags[:1])

pandas.core.frame.DataFrame

III. Extract row 0, 11, 2000 from tags DataFrame.

In [9]:
df_tags.iloc[[0,11,2000],:]

      userId  movieId                tag   timestamp
0         18     4141        Mark Waters  1240597180
11        65     1783      noir thriller  1368149983
2000     910    68554  conspiracy theory  1368043943

IV. Print index, columns of the DataFrame.

In [14]:
df_tags.columns

Index(['userId', 'movieId', 'tag', 'timestamp'], dtype='object')

In [15]:
df_tags.index

RangeIndex(start=0, stop=465564, step=1)

V. Calculate descriptive statistics for the 'ratings' column of the ratings DataFrame. Verify using describe().

In [16]:
df_ratings["rating"].describe()

count    2.000026e+07
mean     3.525529e+00
std      1.051989e+00
min      5.000000e-01
25%      3.000000e+00
50%      3.500000e+00
75%      4.000000e+00
max      5.000000e+00
Name: rating, dtype: float64

VI. Filter out ratings with rating > 5

In [20]:
df_ratings[df_ratings["rating"] > 5]

Empty DataFrame
Columns: [userId, movieId, rating, timestamp]
Index: []

VII. Find how many null values, missing values are present. Deal with them. Print out how many rows have been modified.

In [18]:
df_ratings.isnull().sum()

userId       0
movieId      0
rating       0
timestamp    0
dtype: int64

VIII. Filter out movies from the movies DataFrame that are of type 'Animation'.

In [19]:
df_movies[df_movies["genres"] == "Animation"]

       movieId                                              title     genres
2503      2588                                   Cloudland (1998)  Animation
4906      5002                               Fritz the Cat (1972)  Animation
4907      5003            Nine Lives of Fritz the Cat, The (1974)  Animation
9455     27738                    Cathedral, The (Katedra) (2002)  Animation
9989     32840                                     Vincent (1982)  Animation
13444    66335                  Afro Samurai: Resurrection (2009)  Animation
13858    69469                        Garfield's Pet Force (2009)  Animation
14184    71158                Immigrants (L.A. Dolce Vita) (2008)  Animation
14492    72603                            Merry Madagascar (2009)  Animation
14578    72927                                 Donkey Xote (2007)  Animation
14580    72931                                       Tango (1981)  Animation
14876    74486                                       $9.99 (2008)  Animation
14938    74791   Town Called Panic, A (Panique au village) (2009)  Animation
15085    76709   Spider-Man: The Ultimate Villain Showdown (2002)  Animation
15860    80469                 Superman/Batman: Apocalypse (2010)  Animation
15990    81018          Illusionist, The (L'illusionniste) (2010)  Animation
16551    83603             Fern flowers (Fleur de fougère) (1949)  Animation
16649    84192  Corto Maltese: Ballad of the Salt Sea (Corto M...  Animation
18144    90843  Lavatory Lovestory (Ubornaya istoriya - lyubov...  Animation
18145    90845  Fall of the House of Usher, The (Zánik domu Us...  Animation
18224    91187                                   Millhaven (2010)  Animation
18695    93083                                  Live Music (2009)  Animation
18980    94423  Disney Princess Collection: Jasmine's Enchante...  Animation
19562    96897  Bleach: Fade to Black (Bur&#299;chi Fade to Bl...  Animation
20310    99820  Pokémon the Movie: Black - Victini and Reshira...  Animation
20311    99822  Pokémon the Movie: White - Victini and Zekrom ...  Animation
20314    99832                            Hand, The (Ruka) (1966)  Animation
20527   100509               Tale of Tales (Skazka skazok) (1979)  Animation
20871   102007                    Invincible Iron Man, The (2007)  Animation
20872   102009                       Thor: Tales of Asgard (2011)  Animation
...        ...                                                ...        ...
25207   118948                                   Blackbird (1959)  Animation
25208   118950                                  A Phantasy (1952)  Animation
25211   118956                           Lines: Horizontal (1962)  Animation
25212   118958                                      Mosaic (1966)  Animation
25213   118960                            Begone Dull Care (1949)  Animation
25214   118962                                   Synchromy (1971)  Animation
25538   120853                             Fresh Guacamole (2012)  Animation
25539   120855                                Adam and Dog (2012)  Animation
25663   121302                              Someone's Gaze (2013)  Animation
25718   121600                       Bosko's Parlor Pranks (1934)  Animation
26052   124889    The Adventures of Tom Thumb & Thumbelina (2002)  Animation
26163   125924                           The Periwig-Maker (1999)  Animation
26169   125936                                        Crac (1981)  Animation
26171   125940                                      Syrinx (1966)  Animation
26181   125960                     The Trip to Squash Land (1967)  Animation
26185   125968     It's Christmastime Again, Charlie Brown (1992)  Animation
26189   125976                       Nocturna Artificialia (1979)  Animation
26192   125982                              Trick or Treat (1952)  Animation
26207   126012            The Fat Albert Halloween Special (1977)  Animation
26226   126050                    Stille Nacht I: Dramolet (1988)  Animation
26230   126058            Rehearsals for Extinct Anatomies (1987)  Animation
26236   126070                               Chainsaw Maid (2007)  Animation
26237   126072                        The Little Matchgirl (2006)  Animation
26246   126090                         Hedgehog in the Fog (1975)  Animation
26247   126092                               The Cat's Out (1931)  Animation
26248   126094                Claymation Comedy of Horrors (1991)  Animation
26319   126405        The Adventures of André and Wally B. (1984)  Animation
26809   128864                              Four Sahibjade (2014)  Animation
27103   130394                                  The Mascot (1934)  Animation
27155   130644  The Garden of Sinners - Chapter 5: Paradox Par...  Animation

[83 rows x 3 columns]

IX. Find the average rating of movies.

In [21]:
df_ratings["rating"].mean()

3.5255285642993797

X. Perform an inner join of movies and tags based on movieId.

In [22]:
movie_tags = pd.merge(df_movies, df_tags, how="inner", on="movieId")
movie_tags

,movieId,title,genres,userId,tag,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1644,Watched,1417736680
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1741,computer animation,1183903155
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1741,Disney animated feature,1183933307
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1741,Pixar animation,1183934770
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1741,TÃ©a Leoni does not star in this movie,1245093573
5,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,2299,Pixar,1403306852
6,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,3596,animation,1290312028
7,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,3596,family,1290312032
8,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,3596,Tom Hanks,1290312036
9,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,6233,Pixar,1387079572
10,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,6233,witty,1387079576
11,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,8219,Pixar,1159534063
12,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,10616,adventure,1277357423
13,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,10616,animated,1277357419
14,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,10616,animation,1277357417
15,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,10616,clever,1277357438
16,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,10616,comedy,1277357433
17,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,10616,computer animation,1277357405
18,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,10616,family,1277357449
19,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,10616,fantasy,1277357430
20,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,10616,Tom Hanks,1277357411
21,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,11081,bright,1173304070
22,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,11081,DARING RESCUES,1173304095
23,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,11081,fanciful,1173304058
24,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,11081,HEROIC MISSION,1173304102
25,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,11081,humorous,1173304049
26,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,11081,light,1173304062
27,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,11081,rousing,1173304074
28,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,11081,TOYS COME TO LIFE,1173304091
29,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,11081,UNLIKELY FRIENDSHIPS,1173304106
...,...,...,...,...,...,...
465534,131015,Hellgate (2011),Horror|Thriller,25978,Cary Elwes,1427585540
465535,131015,Hellgate (2011),Horror|Thriller,25978,Demons,1427585566
465536,131015,Hellgate (2011),Horror|Thriller,25978,Exorcism,1427585551
465537,131015,Hellgate (2011),Horror|Thriller,25978,Ghosts,1427585546
465538,131015,Hellgate (2011),Horror|Thriller,25978,Monks,1427585560
465539,131015,Hellgate (2011),Horror|Thriller,25978,nurse,1427585621
465540,131015,Hellgate (2011),Horror|Thriller,25978,psychic,1427585613
465541,131015,Hellgate (2011),Horror|Thriller,25978,slow,1427585575
465542,131015,Hellgate (2011),Horror|Thriller,25978,special effects,1427585690
465543,131015,Hellgate (2011),Horror|Thriller,25978,surfing,1427585592
465544,131015,Hellgate (2011),Horror|Thriller,25978,Thailand,1427585543
465545,131015,Hellgate (2011),Horror|Thriller,25978,William Hurt,1427585696
465546,131031,La liga no es cosa de hombres (1972),(no genres listed),33323,Barcelona,1427641562
465547,131031,La liga no es cosa de hombres (1972),(no genres listed),33323,exploitation,1427641559
465548,131031,La liga no es cosa de hombres (1972),(no genres listed),33323,female football,1427641577
465549,131031,La liga no es cosa de hombres (1972),(no genres listed),33323,football,1427641548
465550,131031,La liga no es cosa de hombres (1972),(no genres listed),33323,Rome,1427641564
465551,131031,La liga no es cosa de hombres (1972),(no genres listed),33323,shorts,1427641571
465552,131031,La liga no es cosa de hombres (1972),(no genres listed),33323,soccer,1427641556
465553,131031,La liga no es cosa de hombres (1972),(no genres listed),33323,transvestite,1427641589
465554,131054,Dinotopia: Quest for the Ruby Sunstone (2005),Children|Fantasy|Sci-Fi,88144,dinosaurs,1427654430
465555,131082,Playground (2009),(no genres listed),92885,documentary,1427654757
465556,131082,Playground (2009),(no genres listed),92885,Yoshitomo Nara,1427654856
465557,131164,Vietnam in HD (2011),War,54560,Vietnam War,1427667401
465558,131170,Parallels (2015),Sci-Fi,88738,alternate reality,1427732804
465559,131258,The Pirates (2014),Adventure,28906,bandits,1427745421
465560,131258,The Pirates (2014),Adventure,28906,Korea,1427745512
465561,131258,The Pirates (2014),Adventure,28906,mutiny,1427745542
465562,131258,The Pirates (2014),Adventure,28906,pirates,1427745419
465563,131258,The Pirates (2014),Adventure,28906,whale,1427745432

XI. Print out the 5 movies that belong to the Comedy genre and have rating greater than 4.

In [ ]:
comedy_rating = pd.merge(df_movies, df_ratings, how="inner", on="movieId")
print(comedy_rating[comedy_rating["genres"] == "Comedy"][comedy_rating["rating"] > 4]["title"].unique()[:5].tolist())

XII. Split 'genres' into multiple columns.

In [10]:
df_movies[["genre1", "genre2", "genre3"]] = df_movies.genres.str.split("|", n=2, expand = True,)
df_movies.head()

,movieId,title,genres,genre1,genre2,genre3
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,Adventure,Animation,Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy,Adventure,Children,Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance,Comedy,Romance,None
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,Comedy,Drama,Romance
4,5,Father of the Bride Part II (1995),Comedy,Comedy,None,None

XIII. Extract year from title e.g. (1995).

In [11]:
df_movies["year"] = df_movies["title"].str.extract("\s\((\d{4})\)$", expand = True)
df_movies.head()

,movieId,title,genres,genre1,genre2,genre3,year
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,Adventure,Animation,Children|Comedy|Fantasy,1995
1,2,Jumanji (1995),Adventure|Children|Fantasy,Adventure,Children,Fantasy,1995
2,3,Grumpier Old Men (1995),Comedy|Romance,Comedy,Romance,None,1995
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,Comedy,Drama,Romance,1995
4,5,Father of the Bride Part II (1995),Comedy,Comedy,None,None,1995

XIV. Select rows based on timestamps later than 2015-02-01.

In [12]:
import datetime
timestamp_input = datetime.datetime(2015, 2, 1).timestamp()
print(timestamp_input)
print(df_tags[df_tags["timestamp"] > timestamp_input])

1422729000.0
        userId  movieId                       tag   timestamp
301        318      260                     1970s  1424472169
302        318      260                   fantasy  1424472169
303        318      260                    sci-fi  1424472169
304        318   115149                    Action  1424534310
305        318   115149                   Revenge  1424534283
306        318   115149              Willem Dafoe  1424534383
324        342      318                masterplan  1423424898
326        342      318             prison escape  1423424898
327        342      318                redemption  1423424898
492        342    54372                    French  1422734628
493        342    54372            murder mystery  1422734632
494        342    54372              twist ending  1422734630
556        342    89118                disturbing  1422734236
557        342    89118              long revenge  1422734239
558        342    89118                   spanish  1422734293
559        342    89118             unpredictable  1422734224
589        342   108190           based on a book  1426978115
590        342   108190                  dystopia  1426978076
591        342   112556           based on a book  1422733895
592        342   112556                  marriage  1422733850
593        342   112556                meticulous  1422733882
594        342   112556                  mindfuck  1422733866
595        342   112556       Neal Patrick Harris  1422733874
596        342   112556             unpredictable  1422733885
1018       370     6975  breaking the fourth wall  1425242234
1019       370    27592                   violent  1425241975
2203       969       97            class conflict  1426754226
2204       969      288                  mindfuck  1426752631
2205       969      288                  paranoid  1426752639
2206       969      288               psychedelic  1426752634
...        ...      ...                       ...         ...
461895  137227   120222         horribly animated  1422821079
461896  137227   120222              nazi imagery  1422821051
461897  137227   120222                    racist  1422821047
461898  137227   120222        racist stereotypes  1422821071
462190  137249      296               influential  1423437040
462191  137249      296                  neo-noir  1423437040
462192  137249      296         quentin tarantino  1423437040
462195  137277   110052     marcello mastroianni,  1422925214
462979  137924    46855                 Criterion  1427722627
462980  137924    46855         French Resistance  1427722622
462981  137924    46855              World War II  1427722614
463004  138063     4355                    Hockey  1424230535
463005  138063   108160                    Hockey  1424230501
463504  138103    67894                   finnish  1423255773
463509  138103    69442                   finnish  1423255750
463544  138103    73501                   finnish  1423255756
463545  138103    74681                   finnish  1423255760
463573  138103    84553                   finnish  1423255764
464786  138301    52042                 espionage  1426032479
464787  138301    52042       resistance movement  1426032481
464788  138301    52042              World War II  1426032485
464958  138301   109487                 ambitious  1423178287
464959  138301   109487                atmosphere  1423178302
464960  138301   109487                plot holes  1423178186
464961  138301   109487                    sci-fi  1423178227
464962  138301   109487           science fiction  1423178255
464963  138301   109487            Self-Indulgent  1423178219
464964  138301   109487                     space  1423178343
464965  138301   109487        visually appealing  1423178319
464966  138301   109487          wasted potential  1423178212

[12168 rows x 4 columns]

XV. Sort the tags DataFrame based on timestamp.

In [14]:
df_tags.sort_values(by = "timestamp")

        userId  movieId                              tag   timestamp
333932  100371     2788                     monty python  1135429210
333927  100371     1732                    coen brothers  1135429236
333924  100371     1206                  stanley kubrick  1135429248
333923  100371     1193                   jack nicholson  1135429371
333939  100371     5004                    peter sellers  1135429399
333922  100371       47                   morgan freeman  1135429412
333921  100371       47                        brad pitt  1135429412
333936  100371     4011                        brad pitt  1135429431
333937  100371     4011                      guy ritchie  1135429431
333920  100371       32                     bruce willis  1135429442
333933  100371     2858                     kevin spacey  1135429466
333931  100371     2329                     fuckoff nazi  1135429508
333930  100371     2329                    edward norton  1135429508
333944  100371     6016                           brazil  1135429520
15903     3797      110                        overrated  1135589075
256663   75141     4642                         Terrible  1135688095
15926     3797     8573             Nonlinear Surrealism  1135936223
68928    16050    38886                             twee  1136036612
68924    16050    38886                         eighties  1136036612
68925    16050    38886                           family  1136036612
68926    16050    38886                         new york  1136036612
68927    16050    38886                        overrated  1136036612
68919    16050     7060                        christian  1136039301
68921    16050     7060                          musical  1136039301
68920    16050     7060                           kitsch  1136039301
68922    16050     7060                        religious  1136039301
68918    16050     6898                            harsh  1136039368
68916    16050     6898                          british  1136039368
68917    16050     6898                            drugs  1136039368
81444    20513    36529                            truth  1136242623
...        ...      ...                              ...         ...
119997   28906   115149                          violent  1427746031
119991   28906   115149                    lack of story  1427746053
119993   28906   115149                     over the top  1427746060
119989   28906   115149                           cheesy  1427746074
405155  123297   128642                              CLV  1427746337
399877  123297     4211                              CLV  1427746709
400993  123297     6419                              CLV  1427746864
401017  123297     6481                              CLV  1427747220
405123  123297   118722                              CLV  1427747321
400106  123297     4573                              CLV  1427747462
150873   42640   115122                     mockumentary  1427748778
150871   42640   115122                           comedy  1427748797
150872   42640   115122                      dark comedy  1427748808
392905  122523     5004                              USA  1427752289
392904  122523     5004                            party  1427752292
290536   88044   106782              unsatisfying ending  1427753000
290534   88044   106782                           Orgies  1427753111
290529   88044   106782                             ENFP  1427753147
290532   88044   106782             Left-Wing Propaganda  1427753266
290533   88044   106782                Left-Wing Writers  1427753621
290528   88044   106782  Economically Illiterate Writers  1427753739
290530   88044   106782                       inaccurate  1427753806
290531   88044   106782                       Jonah Hill  1427753849
290526   88044   106782                           Amoral  1427753913
290527   88044   106782                            crime  1427753921
290535   88044   106782                        profanity  1427754096
288375   87797      215                           Vienna  1427755801
158763   46072     3409                      premonition  1427760726
158780   46072     6058                      premonition  1427760764
339178  102853   115149                    russian mafia  1427771352

[465564 rows x 4 columns]